# Artificial Intelligence - Laboratory 02:Python Introduction part II


##### Review

The following formula computes a _Z score_ and measures how far a single raw data value is from the population mean.

\begin{equation*}
z = \frac{X - \mu }{\sigma }
\end{equation*}

where:
* **_X_** is a single raw data value
* `mu` is the population mean
* `sigma` is the population standard deviation

To find the standard deviation, the equation below comes in hand:

\begin{equation*}
\sigma = \sqrt{\frac{\sum \left | X - \mu \right |^{2}}{N}}
\end{equation*}

where **_N_** is the number of data points in the population.

**a.** Using `sum()` and `list comprehension`, compute the mean and the standard deviation for the population defined below:

In [ ]:
data =  [4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]
print(data)

[4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]


In [ ]:
# Your implementation here:
# using sum and list comprehension compute the mean
mean = sum(data) / len(data) 
# standard deviation
std = sum((x - mean) ** 2 for x in data) / len(data)

print("Mean:", mean)
print("Standard Deviation:", std ** 0.5)


Mean: 12.616666666666667
Standard Deviation: 7.167441818544622


**b.** Define the `z_score()` function and implement the mathematical expression. The obtained values should be stored in a _z score_ values list and rounded to 3 decimals.

In [ ]:
# Your implementatio here:
# z_score() means ....
# Z score formula measures how far a single raw data value is from the population mean (first formula in the lab)
# obtained values should be stored in a z score values list and rounded to 3 decimal
def z_score(x):
    return round((x - mean) / (std ** 0.5), 3) # the 3 means rounding to 3 decimal places

z_scores = [z_score(x) for x in data] # here we create the values list using list comprehension, calling z_score function
print("Z-scores:", z_scores)
    

Z-scores: [-1.132, -1.063, -0.993, -0.923, -0.888, -0.784, 0.367, 0.751, 0.814, 1.17, 1.232, 1.449]


**c.** Add the corresponding elongation of each raw data value into a dictionary.

In [ ]:
# Your implementatio here:
# add the corresponding elongation of each raw data value in a dictionary

#creating a dictionary containing initial values and their z scores
data_dict = {x: z_score(x) for x in data} # using dictionary comprehension
print("Data Dictionary (value: z-score):", data_dict)


Data Dictionary (value: z-score): {4.5: -1.132, 5: -1.063, 5.5: -0.993, 6: -0.923, 6.25: -0.888, 7: -0.784, 15.25: 0.367, 18: 0.751, 18.45: 0.814, 21: 1.17, 21.45: 1.232, 23: 1.449}


## Classes

The object-oriented programming paradigm in Python helps with structuring programs into `individual objects`. But how?

* An Object **O** from a class **C** has a set of properties **_p_** and actions **_a_**.

* The functions of a class are called `methods`. Their responsibility is to model the data corresponding to a given object.

* The objects of a class are known as `instances` and represent the source of collecting data.

```python

class EmptyClas:
    """
    This is a class without variables and methods
    """
    pass # The keyword pass is a placeholder


class MyClass:
    # A class variable
    name = 'My Class'
    
    def my_method(self, my_var):
        # An instance variable
        self.my_instance = my_var
```

In [ ]:
# Implement Task 0 b and c here:

class ScientificConference:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        b. Add new attribute `papers`
        """
        """ *b.** Create a new attribute for the `class ScientificConference`, which is a dictionary
        passed as a parameter to the instances of the class and holds all of the papers of the conference.

        _Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

        _Please handle duplicate entries by removing them!_"""
        #check if `papers` is `None` in `__init__` and set it to `{}` instead
        # also, handle duplicate entries by removing them
        papers = None
        self.papers = papers if papers is not None else {}
        self.papers = {k: v for k, v in self.papers.items() if v not in self.papers.values()}


    def add_manuscript(self, title, researcher):
        #**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. 
        # Please consider using the _researcher_ as a `key` and the _title_ as `values`.
        if researcher not in self.papers:
            self.papers[researcher] = []
        if title not in self.papers[researcher]:
            self.papers[researcher].append(title)

    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for author, papers in self.papers.items():
            result += f'{author}: {", ".join([str(paper) for paper in papers])} \n'
        return result

<>:4: SyntaxWarning: invalid escape sequence '\ '
<>:4: SyntaxWarning: invalid escape sequence '\ '
C:\Users\PC\AppData\Local\Temp\ipykernel_7832\1036726511.py:4: SyntaxWarning: invalid escape sequence '\ '
  """


### Task 0

**a.** Define two new `instances` of the `class ScientificConference` and return their representations.

Your output should look like:

`Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.`

_Hint:_ `instance.attribute` helps you extracting a certain property.

In [ ]:
# Your implementation here

#two new instances of the class ScientificConference
conf1 = ScientificConference("Mamaliguta cu ciolan stiintific", 1998)
conf2 = ScientificConference("Ambiguitate cosmica inferioara", 2008)
#returning representation of conf1 and conf2 (but this needs to be done after solving task 0 b and c)
# shal return the stuff from _str_ method
print(conf1)
print(conf2)


Mamaliguta cu ciolan stiintific 1998: 

Ambiguitate cosmica inferioara 2008: 



**b.** Create a new attribute for the `class ScientificConference`, which is a dictionary passed as a parameter to the instances of the class and holds all of the papers of the conference.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

_Please handle duplicate entries by removing them!_

**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. Please consider using the _researcher_ as a `key` and the _title_ as `values`.

In [ ]:
# Verify here if your add_manuscript method works: add an item & print it

conference = ScientificConference("AI Conference", 2023)
conference.add_manuscript("AI for FILS students", "Alice")
print(conference)

AI Conference 2023: 
Alice: AI for FILS students 



### Task 1

**a.** Define the class `Person` which stores the `title`, `name` and `surname` of a person.

The _tuple_ `allowed_titles` is a class variable which helps to verify if the title of a person is "Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS" or "Computer Scientist".

An error is returned if the title is not valid.

Use `__str__` defined below:

```python
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
```

In [ ]:
#Define class Person wich stores title, name and surname. Tuple allowed_titles is a variable wich verify if the 
# title is correct: Mr, Mrs, Ms, Senior Researcher, Professor of CS or Computer Scientist
# Your implementation here
class Person:
    allowed_titles = ("Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS", "Computer Scientist")

    def __init__(self, title, name, surname):
        if title not in Person.allowed_titles:
            raise ValueError("The title isn't right") # given at start of exercise, I guess this it what it was meant for
        self.title = title
        self.name = name
        self.surname = surname
    
    # given by professor in the example
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name


**b.** Create two instances of the class Person and verify if the following entries are valid:

* _Mr Ian Goodfellow_,
* _SeniorResearcher Tomas Mikolov._

In [ ]:
# Your implementation here

person1 = Person("Mr", "Ian", "Goodfellow")
print(person1)
# I put a blank space between senior and researcher to take care of my OCD
person2 = Person("Senior Researcher", "Tomas", "Mikolov")
print(person2)

Mr Goodfellow Ian
Senior Researcher Mikolov Tomas


### Task 2

In `ScientificConference` we have been using the paper parameter as a string, but this concept requires a detailed structure.

Introduce a new class, `Paper`, which has the following attributes:

* `authors`, 
* `title`, 
* `a_id`,
* `year`, 
* `status` (published or in development), 
* `peer_rating` (Excellent, Good, Fair, Poor, Barely Acceptable, Unacceptable).

In [ ]:
class Paper:
    def __init__(self, authors, title, a_id, status, year, peer_rating):
        self.authors = authors  
        self.title = title
        self.a_id = a_id
        self.status = status  
        self.year = year
        self.peer_rating = peer_rating  # Excelent, Good, Fair, Poor, Barely Acceptable, Unacceptable


    def __str__(self):
        return  f'{self.title}, {", ".join([author for author in self.authors])} et al. ({self.year}), a_id: '\
                f'{self.a_id}, status: {self.status}, rating: {self.peer_rating}'

## Inheritence

In Object-Oriented programming, this concept enables us to transfer the methods and the properties of a class to another class.

### Task 3

Create a class named `Researcher`, which inherits the properties and methods from the `Person` class. Besides, this class has an additional parameter, `papers` which is `None` by default.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `[]` instead.

```python
class Researcher(Person):
    def __init__('Add arguments'):
        super().__init__(title, name, surname)
```

In [ ]:
# Define your first researcher
# Expected output: Senior Researcher Tomas Mikolov

class Researcher(Person):
    # inherits properties and methods from the Person class
    def __init__(self, title, name, surname, papers=None, co_authored=False):
        self.co_authored = co_authored
        super().__init__(title, name, surname) 
        self.papers = papers if papers is not None else []

    """ Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
    _Hint:_ Use `self.co_authored = False` inside the `__init__` function."""
    def verify_co_authorship(self, other_researcher, papers):
        self.co_authored = False
        for paper in papers:
            if self in paper.authors and other_researcher in paper.authors:
                self.co_authored = True
                break
        return self.co_authored

    """
    Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

    For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`   print_papers(researcher2.get_collab(researcher3))` should output:

    _Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

    _Note:_ This function helps you to print the papers from a given list.

    ```python
    def print_papers(paper_list):
        for paper in paper_list:
            print(paper)
    ```
    """
    def get_collab(self, other_researcher, papers):
        collab_papers = []
        for paper in papers:
            if self in paper.authors and other_researcher in paper.authors:
                collab_papers.append(paper)
        return collab_papers

    def print_papers(paper_list):
        for paper in paper_list:
            print(paper)


### Task 4

Consider the following scientists:

1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yann LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.

_Note:_ Let us consider "Mr" as a default title for the researchers without a specific caption. Also, for the id of a paper, please use only integers from the provided links.

**a.** Define the next 5 scientists and use them in your `paper` objects.

**b.** Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
_Hint:_ Use `self.co_authored = False` inside the `__init__` function.

**c.** Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`print_papers(researcher2.get_collab(researcher3))` should output:

_Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

_Note:_ This function helps you to print the papers from a given list.

```python
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)
```

**d.** What are the papers written by Yoshua Bengio?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent`

`Paper On the difficulty of training recurrent neural networks, Mr Razvan Pascanu et al. (2013), a_id: 5063, status: published, rating: Excelent`

**e.** Did he ever co-author a paper?

**f.** Which papers are published by Yann LeCun?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Good`

In [ ]:
# define next 5 scrientinsts and use them in your paper objects
# Your implementation here
"""
1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yann LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.
"""
yann = Researcher("Mr", "Yann", "LeCun")
yoshua = Researcher("Professor of CS", "Yoshua", "Bengio")
geoffrey = Researcher("Mr", "Geoffrey", "Hinton")
razvan = Researcher("Mr", "Razvan", "Pascanu")
tomas = Researcher("Senior Researcher", "Tomas", "Mikolov")
ian = Researcher("Mr", "Ian", "Goodfellow")

papers = [
    Paper([yann, yoshua, geoffrey], "Deep Learning", 14539, "published", 2015, "Excelent"),
    Paper([razvan, tomas, yoshua], "On the difficulty of training recurrent neural networks", 5063, "published", 2013, "Excelent"),
    Paper([ian, yoshua], "Generative Adversarial Nets", 5423, "published", 2015, "Excelent"),
    Paper([yann], "Handwritten Digit Recognition with a Back-Propagation Network", 293, "published", 1989, "Good"),
    Paper([geoffrey], "Gated Softmax Classification", 3895, "published", 2010, "Good"),
]

# helper to print a Paper using researcher __str__ for authors
def print_paper(p):
    authors_str = ", ".join(str(a) for a in p.authors)
    print(f"{p.title}, {authors_str} et al. ({p.year}), a_id: {p.a_id}, status: {p.status}, rating: {p.peer_rating}")

# function to get papers by a researcher
def get_papers_by_researcher(researcher, papers_list):
    return [p for p in papers_list if researcher in p.authors]

# solving subtask d) 
# (d) Papers written by Yoshua Bengio
yoshua_papers = get_papers_by_researcher(yoshua, papers)
for p in yoshua_papers:
    print_paper(p)
print("----------------------")
# (e) Did he ever co-author a paper? (uses Researcher.verify_co_authorship)
# check co-authorship with any other researcher, e.g. Ian Goodfellow
print("Co-authored with Ian Goodfellow?:", yoshua.verify_co_authorship(ian, papers))
print("----------------------")
# (f) Papers published by Yann LeCun
yann_papers = get_papers_by_researcher(yann, papers)
for p in yann_papers:
    print_paper(p)



Deep Learning, Mr LeCun Yann, Professor of CS Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), a_id: 14539, status: published, rating: Excelent
On the difficulty of training recurrent neural networks, Mr Pascanu Razvan, Senior Researcher Mikolov Tomas, Professor of CS Bengio Yoshua et al. (2013), a_id: 5063, status: published, rating: Excelent
Generative Adversarial Nets, Mr Goodfellow Ian, Professor of CS Bengio Yoshua et al. (2015), a_id: 5423, status: published, rating: Excelent
----------------------
Co-authored with Ian Goodfellow?: True
----------------------
Deep Learning, Mr LeCun Yann, Professor of CS Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), a_id: 14539, status: published, rating: Excelent
Handwritten Digit Recognition with a Back-Propagation Network, Mr LeCun Yann et al. (1989), a_id: 293, status: published, rating: Good


### Task 5 

Consider an updated version of the `ScientificConference` class, which should have a modified version of the function `add_manuscript`.

Use the `status` and the `peer_rating` variables as a **threshold** to add papers in your `papers` dictionary. The conferences will only be accepting `Excelent` papers. For this case, the dictionary has the year of the paper as `key`, and the `values` are stored as a tuple of `(researcher, manuscript)`. For the papers which don't satisfy this condition, the message _"Please review your submission."_ is displayed.

For papers submitted in 2015, when printing the conference, the `str` function should output:

```
NeurIPS 2020: 
2015: 
Mr Ian Goodfellow: Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), id: 5423, status: published, rating: Excelent 
Computer Scientist Yann LeCun: Deep Learning, Computer Scientist Yann LeCun et al. (2015), id: 14539, status: published, rating: Excelent
```

In [ ]:
class ScientificConferenceUpdate:
    """ 
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        Add new attribute `papers`
        """
        self.papers = {}
    
    def add_manuscript(self, manuscript, researcher):
        if getattr(manuscript, "status", None) == "published" and getattr(manuscript, "peer_rating", None) == "Excelent":
            yr = manuscript.year
            self.papers.setdefault(yr, [])
            # avoid duplicates by checking paper a_id
            if not any((p.a_id == manuscript.a_id) for (_, p) in self.papers[yr]):
                self.papers[yr].append((researcher, manuscript))
        else:
            print("Please review your submission.")

        
    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = f"{self.name} {self.year}: \n"
        for year in sorted(self.papers):
            result += f"{year}: \n"
            for (author, paper) in self.papers[year]:
                authors_str = ", ".join(str(a) for a in paper.authors)
                # match expected printed format (includes id, status, rating)
                result += f"{str(author)}: {paper.title}, {authors_str} et al. ({paper.year}), id: {paper.a_id}, status: {paper.status}, rating: {paper.peer_rating} \n"
        return result
    
#test
conf = ScientificConferenceUpdate("NeurIPS", 2020)
conf.add_manuscript(papers[2], ian)    # Generative Adversarial Nets (accepted)
conf.add_manuscript(papers[0], yann)   # Deep Learning (accepted)
conf.add_manuscript(papers[3], yann)   # Handwritten Digit (peer_rating 'Good' -> rejected)
print(conf)


<>:2: SyntaxWarning: invalid escape sequence '\ '
<>:2: SyntaxWarning: invalid escape sequence '\ '


Please review your submission.
NeurIPS 2020: 
2015: 
Mr Goodfellow Ian: Generative Adversarial Nets, Mr Goodfellow Ian, Professor of CS Bengio Yoshua et al. (2015), id: 5423, status: published, rating: Excelent 
Mr LeCun Yann: Deep Learning, Mr LeCun Yann, Professor of CS Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), id: 14539, status: published, rating: Excelent 



C:\Users\PC\AppData\Local\Temp\ipykernel_7832\2962328493.py:2: SyntaxWarning: invalid escape sequence '\ '
  """
